general.import = [ "~/.local/state/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Maple Mono Normal NF" }
bold = { family = "Maple Mono Normal NF" }
italic = { family = "Maple Mono Normal NF" }
size = 14

[terminal]
shell = "/usr/bin/zsh"
osc52 = "CopyPaste"

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 1.0
dynamic_title = true

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 5

[keyboard]
bindings = [
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" },
{ key = "Return", mods = "Shift", chars = "\u001B[13;2u" }
]

